### ISSUE TITLE
Need new terminal session after OS X setup instructions

### ISSUE THREAD

**Issue by rahatarmanahmed** [intermezzOS/book#104]
I ran into one particular issue that came from not reloading my shell:

``` sh
$ nasm -v
NASM version 0.98.40 (Apple Computer, Inc. build 11) compiled on Feb 10 2016

$ brew install nasm
==> Downloading https://homebrew.bintray.com/bottles/nasm-2.11.08.el_capitan.bot
Already downloaded: /Library/Caches/Homebrew/nasm-2.11.08.el_capitan.bottle.tar.gz
==> Pouring nasm-2.11.08.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/nasm/2.11.08: 25 files, 2.2M

$ nasm -v
NASM version 0.98.40 (Apple Computer, Inc. build 11) compiled on Feb 10 2016
```

Now when I go to assemble the multiboot headers in ch 3.1.:

``` sh
$ nasm -f elf64 multiboot_header.asm
nasm: fatal: unrecognised output format `elf64' - use -hf for a list
type `nasm -h' for help
```

But if I reload the shell:

``` sh
$ nasm -v
NASM version 2.11.08 compiled on Sep 22 2015

$ nasm -f elf64 multiboot_header.asm
# assembling is a-ok
```

I'm not sure why homebrew doesn't put the new nasm in the current context after you install, or if this is just an issue with my laptop specifically. If this is normal behavior, a note to reload the shell at the end of ch 2.2. would be helpful.

**Comment by bjorn3** [comment]
Maybe brew puts a new location in the PATH, which it can't change for existing sessions.

**Comment by ZymoticB** [comment]
This may be caused by having nasm already installed and it having been run in the shell in question before the brew install. This would caused bash to have cached the name -> path to binary. You can reset this cache with `hash -r`.

May be something worth adding at the end of `osx-install.md`

**Comment by DavidCai1111** [comment]
I met this issue in macOS 10.12.4 too. Maybe it's worth adding to `osx-install.md` ?

**Comment by steveklabnik** [comment]
I'm not working on the first edition anymore, so I'm going to give this a close. The second edition doesn't need this stuff anymore, and is much easier to work with. If someone wants to send in a PR to fix up the first edition, please feel free!
