### ISSUE TITLE
book/src/hello-world.md has some assembly that's probably not safe

### ISSUE THREAD

**Issue by Jimmio92** [intermezzOS/book#105]
Just calling x86's hlt in a bootloader is likely not safe as it will continue when the first interrupt arrives assuming interrupts are on (and they will arrive a lot as the system timer interrupts a lot.. and so would the keyboard.. and any event the BIOS understands). It's much safer to disable interrupts first with cli.

**Comment by steveklabnik** [comment]
Well, we aren't in a bootloader, we have GRUB for that. Does GRUB leave interrupts enabled? I would assume that they're not on, given that if you `sti`, you get a triple fault, since we haven't set up an IDT at all.

**Comment by steveklabnik** [comment]
I'm not working on the first edition anymore, so I'm going to give this a close. This stuff isn't in the second edition yet, and it's not likely to make it exactly. If someone wants to send in a PR to fix up the first edition, please feel free!
