### ISSUE TITLE
Questions and clarification of paging table addresses

### ISSUE THREAD

**Issue by Digipom** [intermezzOS/book#108]
Hi,

The explanation for this part:

>  ; Point the first entry of the level 4 page table to the first entry in the
>     ; p3 table
>     mov eax, p3_table
>     or eax, 0b11
>     mov dword [p4_table + 0], eax

Says that

> Now, we defined p3_table in the BSS section, which means that it will start as all zeroes. So when we or with 0b11, it means that the first two bits will be set to one, keeping the rest as zeroes.

So here it seems like we moved the value of whatever was at p3_table there. However, it seems that it would make more logical sense if this was the address of the p3_table and later on the text does seem to confirm that this is what's going on:

> We have to put the address of the level four page table in a special register
> 
> ```
> ; move page table address to cr3
> mov eax, p4_table
> ```

So I found this somewhat confusing because I wasn't sure if we were dealing with values or addresses.

Aside from that I noticed two other things in the page:
- I think it could also be helpful to clarify the bit structure of all 32 bits of the page table entry just to show which bits do what, 
- In a few places, the ASM seems to operate on eax by default (i.e.: `mul ecx'). Might be good to note that.

Again this is pretty good work so far, really enjoying following this. :)

**Comment by steveklabnik** [comment]
Labels should be addresses, but ... you're right. Hm...

> I think it could also be helpful to clarify the bit structure of all 32 bits of the page table entry just to show which bits do what, 

I do think this would be a good idea, but at some point, we're going to come back and set up a "real" paging system, not a simple identity mapping, so I figured we'd wait till then. I really want to get to Rust!

> In a few places, the ASM seems to operate on eax by default (i.e.: `mul ecx'). Might be good to note that.

I tried to, but I'll go back and double check that I actually did :)

**Comment by Digipom** [comment]
> In a few places, the ASM seems to operate on eax by default (i.e.: `mul ecx'). Might be good to note that.
> I tried to, but I'll go back and double check that I actually did :)

Indeed you did, I must have not grokked it the first time. :) Please disregard this part.

**Comment by Digipom** [comment]
Closing due to https://github.com/intermezzOS/book/pull/109.
