### ISSUE TITLE
src/hello-world.md: word or byte

### ISSUE THREAD

**Issue by gokhanettin** [intermezzOS/book#113]
The book clearly says a word is 16 bits below.
src/multiboot-headers.md:

> Finally, the dd. It’s short for ‘define double word’. It declares that we’re going to stick some 32-bit data at this location. Remember, when x86 first started, it was a 16-bit architecture set. That meant that the amount of data that could be held in a CPU register (or one ‘word’ as it's commonly known) was 16 bits. To transition to a 32-bit architecture without losing backwards compatibility, x86 got the concept of a ‘double word’ or double 16 bits.

I am not sure following paragraph is true.
src/hello-world.md:

> Okay, so we copied four hexadecimal digits into memory, right? For our H. 0248. A hexadecimal digit has sixteen values, so two of them are 32. Since we need one word for the colors, and one word for the H, that’s two words. Hence, if our first memory position is at 0, the second letter will start at 2.

http://wiki.osdev.org/Printing_To_Screen
Here on this page it says "Text mode memory takes two **bytes** for every "character" on screen. One is the ASCII code **byte**, the other the attribute **byte**."

And 0x0248 is two bytes( i.e. 16 bits), not two words(i.e. 32 bits).

I suspect we should say "...we need one byte for the colors, and one byte for the H, that is two bytes."
Memory position is increased by 2, not because that's two words, but two bytes.

**Comment by steveklabnik** [comment]
Yes, this would seem to be a bug. gah!

**Comment by steveklabnik** [comment]
I'm not working on the first edition anymore, so I'm going to give this a close. This stuff isn't in the second edition yet, and it's not likely to make it exactly. If someone wants to send in a PR to fix up the first edition, please feel free!
