### ISSUE TITLE
Mac OS X setup script doesn't work with zsh?

### ISSUE THREAD

**Issue by corincerami** [intermezzOS/book#114]
I think the OS X script may be incompatible with zsh, although I haven't quite pinned down exactly what about it is the problem. When I ran it using bash everything went smoothly, which leads me to believe it actually is some incompatibility between bash and zsh.

It would be great if the script could be updated to work with either of these, but I realize at some point there are plenty of shells people might want it to work with, so perhaps at least mentioning that it should be run with bash would suffice.

**Comment by roneesh** [comment]
I ran the OS X script using zsh and haven't encountered any specific problems with the script itself. Is there a line that's specifically off that I could take a look at? Or is there something that is failing to download?

**Comment by steveklabnik** [comment]
I'm not working on the first edition anymore, so I'm going to give this a close. The second edition works on OS X without needing this stuff, and is much easier to build. If someone wants to send in a PR to fix up the first edition, please feel free!
