### ISSUE TITLE
Shifting bits

### ISSUE THREAD

**Issue by dhardy** [intermezzOS/book#121]
Why do people keep talking about `1 << 5` as if it has the _fifth_ bit set? It's the _sixth_, and [I clarified already](http://intermezzos.github.io/book/paging.html#Enable%20paging).

`1 << 0` is 1, with the _first_ bit set; `1 << 1` has bit 1+1=2 set. There are a bunch of errors along these lines in issues, [this section](http://intermezzos.github.io/book/setting-up-a-gdt.html#Setting%20up%20a%20code%20segment), etc. Is this the norm with systems programming?

**Comment by phil-opp** [comment]
Usually we count from zero. So `1 << 0` has the zeroth bit set and `1 << 63` the 63th bit. Equally, `1 << 5` has the fifth bit set.

**Comment by dhardy** [comment]
You can't do that... damn, you did, and I'm sure you weren't the first.

But seriously, ask any non-programmer what the first element is in the list `[0, 1, 2, 3]`. Sure, indexes and offsets are one thing, but _first_ means _first_, _second_ means one-after-first, and there is no such thing as "zeroth".

Note: I have a lot of programming experience, but did my bachelor in maths. Should there be a clarification that the article is a bit wooly about the meaning of "first"?

**Comment by phil-opp** [comment]
Citing [Wikipedia](https://en.wikipedia.org/wiki/Zero-based_numbering):

> Zero-based numbering or index origin = 0 is a way of numbering in which the initial element of a sequence is assigned the index 0, rather than the index 1 as is typical in everyday non-programming circumstances. Under zero-based numbering, **the initial element is sometimes termed the zeroth element, rather than the first element**; zeroth is a coined ordinal number corresponding to the number zero. […] There is not wide agreement regarding the correctness of using zero as an ordinal (nor regarding the use of the term zeroth) as **it creates ambiguity for all subsequent elements of the sequence when lacking context**.

(emphasis mine)

So it's somewhat standard and somewhat ambiguous. However, I'm pretty sure that calling bit 5 “the sixth bit” would lead to much confusion.

**Comment by steveklabnik** [comment]
Hm, I am not sure. This is tough.

**Comment by dhardy** [comment]
Maybe it's simpler to avoid using ordinals altogether?

Say things like: _remember, `1 << 44` means one followed by 44 zeros in binary,_ and _we will use the notation that "bit n" means one followed by n binary zeros_.

**Comment by courajs** [comment]
I try to avoid ordinals when talking about 0-based numbers, opting for "element N". Also, finding an excuse to mention "element 0" or "bit 0" within the same context can make things more clear.

**Comment by steveklabnik** [comment]
I'm not working on the first edition anymore, so I'm going to give this a close. This stuff isn't in the second edition yet, and it's not likely to make it exactly. If someone wants to send in a PR to fix up the first edition, please feel free!
