### ISSUE TITLE
Contradictions on GDT setup

### ISSUE THREAD

**Issue by xerz-one** [intermezzOS/book#122]
I've been reading the book for a few days, and just got stuck at "[Setting up a GDT](http://intermezzos.github.io/book/setting-up-a-gdt.html#Setting%20up%20a%20code%20segment)", because the section seems incomplete and contradicting. In short, it is suggesting me to write the following code at "Setting up a code segment" and "Setting up a data segment":

``` assembly
.code: equ $ - gdt64
    dq (1<<44) | (1<<47) | (1<<41) | (1<<43) | (1<<53)
.data: equ $ - gdt64
    dq (1<<44) | (1<<47) | (1<<41)
```

...yet immediately below, at "Putting it all together", the following code seems to come out of nowhere:

``` assembly
.code: equ $ - gdt64
    dq (1<<44) | (1<<47) | (1<<41)
.data: equ $ - gdt64
    dq (1<<44) | (1<<47) | (1<<41)
    dq (1<<44) | (1<<47) | (1<<41) | (1<<43) | (1<<53)
    dq (1<<44) | (1<<47) | (1<<41)
```

This should probably be considered as a bug or a TODO.

**Comment by xerz-one** [comment]
Just tested both pieces of code (still not an expert!) Seems that this is a bug, and that the 1st piece of code is the correct one.

**Comment by steveklabnik** [comment]
Yes, I believe that this is an error of some kind; I probably screwed it up in editing. The first code is correct.
