### ISSUE TITLE
Mistake in Paging section

### ISSUE THREAD

**Issue by Seeker14491** [intermezzOS/book#130]
In the "Paging" section, there is the following paragraph:

"Now, we defined `p3_table` in the BSS section, which means that it will start as all zeroes. So when we `or` with `0b11`, it means that the first two bits will be set to one, keeping the rest as zeroes."

and the relevant code:

``` asm
global start

section .text
bits 32
start:
  ; Point the first entry of the level 4 page table to the first entry in the
  ; p3 table
  mov eax, p3_table
  or eax, 0b11
  mov dword [p4_table + 0], eax

section .bss

align 4096

p4_table:
  resb 4096
p3_table:
  resb 4096
p2_table:
  resb 4096
```

As I understand it, `mov eax, p3_table` moves the _address_ of `p3_table` into `eax`, not its value. So we are not `or`ing `0b11` with zero. If we were, we could just replace all of 

``` asm
mov eax, p3_table
or eax, 0b11
mov dword [p4_table + 0], eax
```

with the single instruction

``` asm
mov dword [p4_table + 0], 0b11
```

**Comment by steveklabnik** [comment]
I'm not working on the first edition anymore, so I'm going to give this a close. This stuff isn't in the second edition yet, and it's not likely to make it exactly. If someone wants to send in a PR to fix up the first edition, please feel free!
