### ISSUE TITLE
Bit / Byte error in Paging section

### ISSUE THREAD

**Issue by Seeker14491** [intermezzOS/book#131]
Here is an excerpt from this section:

---

Just like before, we are now writing the value in `eax` to a location. But instead of it being just `p2_table + 0`, we’re adding `ecx * 8` Remember, `ecx` is our loop counter. Each entry is eight bytes in size: `0b10000011`. So we need to multiply the counter by eight, and then add it to `p2_table`. Let’s take a closer look: let’s assume `p2_table` is zero, to make the math easier:

```
p2_table              0    0     0     0     0
ecx                   0    1     2     3     4
ecx * 8               0    8    16    24    32
p2_table + ecx * 8    0    8    16    24    32
```

We skip eight spaces each time, so we have room for all eight bits of the page table.

---

"Each entry is eight bytes in size: `0b10000011`."
- `0b10000011` is 8 bits, or 1 byte, so I don't see how it's related to each entry being 8 bytes.

"We skip eight spaces each time, so we have room for all eight bits of the page table."
- I think this should say "We skip eight spaces each time, so we have room for all eight **bytes** of the page table **entry**."

**Comment by steveklabnik** [comment]
I'm not working on the first edition anymore, so I'm going to give this a close. This stuff isn't in the second edition yet, and it's not likely to make it exactly. If someone wants to send in a PR to fix up the first edition, please feel free!
