### ISSUE TITLE
4.1 - Paging concepts questions

### ISSUE THREAD

**Issue by roneesh** [intermezzOS/book#135]
Iv'e read over the paging section a few times, but I still have some conceptual gaps. Can you tell me if I'm understanding things right?

I understand that we use paging to map a 64-bit number to a place in physical memory, which is much smaller than our 64-bit address space.

But you also write in this paragraph:

> How should we do our mapping of physical to virtual addresses? You can make this easy, or complex, and it depends on exactly what you want your OS to be good at. Some strategies are better than others, depending on the kinds of programs you expect to be running. We’re going to keep it simple, and use a strategy called ‘identity mapping’. This means that every virtual address will map to a physical address of the same number. Nothing fancy.

This seems to contain a lot of nuance packed in. First does "Some strategies are better than others..." mean there are multiple ways to implement paging? Second, does identity mapping imply that we'll only use as many virtual addresses as we directly have in physical addresses? Meaning that if we have 8GB of ram on computer we'll only have 1,000,000 address spaces to work with in our OS? (Because 8 GB / 64 bit is 1,000,000)? Are there other strategies that let us map 1 physical address to a full range of virtual addresses?

My second questions concern the implementation of paging:

Are we only implementing 4 pages of memory? Since each page is 4096 bytes, that means each page has 512 addresses (4096 bytes / 64 bits), and that's it? Is our OS only working with 2048 addresses? That seems kind of small? But then again if we're only doing this to get our OS into Long Mode, do we just need to set up a single example of paging to trick Grub into running it in 'long mode'. And if the latter is the case, then is our study of paging for a computer memory pertinent to how our OS really handles memory?

**Comment by steveklabnik** [comment]
> This seems to contain a lot of nuance packed in.

Yeah, you're right; it's tough. I was trying to both explain paging in general, while also not getting to deep in the weeds. It could use some work.

> First does "Some strategies are better than others..." mean there are multiple ways to implement paging?

Yup!

> Second, does identity mapping imply that we'll only use as many virtual addresses as we directly have in physical addresses? 

Correct.

> Are there other strategies that let us map 1 physical address to a full range of virtual addresses?

The mapping goes the other way; it's mapping virtual addresses to physical ones. There are other schemes that let you map multiple virtual addresses to the same physical address, and in fact, I hope to eventually do that. (This is commonly used to keep one copy of the kernel in physical memory, but to pretend like each running application has its own copy)

> Are we only implementing 4 pages of memory? 

Yes. For now!

> But then again if we're only doing this to get our OS into Long Mode, do we just need to set up a single example of paging to trick Grub into running it in 'long mode'. 

Exactly. In the future, we will re-map everything in a more complex manner, but the purpose here is to get the absolute minimum working to get into long mode.

> And if the latter is the case, then is our study of paging for a computer memory pertinent to how our OS really handles memory?

I think this ties into my original comment; maybe there should be less explanation here, and we can put it into the eventual section when we properly implement paging. Hmm...

**Comment by roneesh** [comment]
Thanks, these clarifications help a lot!

When it comes to what our page table code sets up, I'm kind of confused (I've re-read and checked out some other reference literature)

But in this code:

```
    mov eax, p3_table
    or eax, 0b11 ;
    mov dword [p4_table + 0], eax

    ; Point the first entry of the level 3 page table to the first entry in the
    ; p2 table
    mov eax, p2_table
    or eax, 0b11
    mov dword [p3_table + 0], eax

    ; point each page table level two entry to a page
    mov ecx, 0         ; counter variable
.map_p2_table:
    mov eax, 0x200000  ; 2MiB
    mul ecx
    or eax, 0b10000011
    mov [p2_table + ecx * 8], eax

    inc ecx
    cmp ecx, 512
    jne .map_p2_table
```

We seem to be doing the following:
1. Move p3_table into eax, and p3_table is just 4096 bytes of all zeroes
2. or with binary 11, so the first two bits are 11, and then the rest of the 32,766 ( (4096 \* 8) - first two bits that are 11) bits are zeroes
3. in `mov dword [p4_table + 0], eax` we're pointing an address to our p3_table? I think this line is what is not clear to me, dword is a small value, so it's an address or something?
4. Repeat for p2, except  p3_table address at 0 will point to p2 table?
5. Finally p2_table seems to break the mold here and do something 512 times, but I can't quite figure out what? It seems like pages 3 and 4 are just 4096 bytes, but page 2 is gigantic. 

Overall, I think I just don't know what the architecture is that I'm setting up here. I've googled around for some visuals on 'identity paging', but nothing that really clarifies what we're building with our assembly code. Is there any clarification you can provide that might be helpful?

**Comment by steveklabnik** [comment]
This code is @phil-opp 's , and he has awesome visuals: http://os.phil-opp.com/entering-longmode.html#paging

I actually think his explanation is much better than mine here, and maybe reading it will help clarify things more. Give that a shot and then we can talk about it?

**Comment by steveklabnik** [comment]
Oh, and

> Finally p2_table seems to break the mold here and do something 512 times, 

I forgot about this, and made a mistake earlier:

> > Are we only implementing 4 pages of memory?
> 
> Yes. For now!

We actually are mapping more than this; we're only mapping a few of the higher-level tables, but we are making 512 of the final levels, so we actually do have a lot more memory than that. Sigh. This is one of the parts of the whole thing I'm personally weakest at.

**Comment by roneesh** [comment]
Ahh, Phil's article definitely helps. Tons of questions still abound, but I think at that point you need to do a deep dive into paging for operating systems rather than build an OS in Rust.

I'll take away as my positives that I understand a lot more assembly after reading this, but that perhaps It'll take me some time to understand _why_ our paging architecture is the way it is.

**Comment by WillEngler** [comment]
FWIW, I found this bit confusing:

> So now we have an imbalance. We have only roughly 8.5 billion actual physical memory slots in an 8GB machine but quintillions of possible addresses we can make.
> 
> How can we resolve this imbalance? We don't want to be able to address memory that doesn't exist!

I didn't understand why that was _our_ problem as OS developers. What good does it do to accept all 2^64 addresses? Just don't address memory that doesn't exist, silly application developers ;) 

One idea on how to motivate paging: maybe build off of your discussion on how you have a machine with 8GB of RAM, but the reader might have 4GB or 16GB. If we could only use the physical address space, then programs would all have to be built against the lowest amount of RAM on any computer. If a program is built to work on my 4GB machine, it could never address the extra 4GB worth of addresses on your machine with 8GB of RAM. Half of your addresses would never be used. What a waste! We need a way to take advantage of machines with more RAM while also ensuring our programs don't reference nonexistent addresses on machines with less RAM. 

That motivation has problems of its own. I'm trying to get at something that shows we're not implementing paging as a sort of error handling. But as you note, it's tough to not get deep into the weeds here.

**Comment by steveklabnik** [comment]
I'm not working on the first edition anymore, so I'm going to give this a close. This stuff isn't in the second edition yet, and it's not likely to make it exactly. If someone wants to send in a PR to fix up the first edition, please feel free!
