### ISSUE TITLE
Assumed Knowledge at Beginning of Book 

### ISSUE THREAD

**Issue by rylev** [intermezzOS/book#14]
Some things that I think the book assumes the reader is 100% comfortable with although it's not unreasonable to think that they might not be:
- **different architectures** - someone who writes Javascript all day, for example, might be a little unfamiliar with what is meant by the x86 architecture. We should probably include a small section discussing the ideas that there are different CPU architectures, that since we're working at such a low level we have to worry about such things and that we are targeting (at first) just Intel's x86 architecture.
- **unix based references** -  the book (quite understandably) leans heavily on examples from the unix world. Including some more Windows friendly examples along with unix based references may make things more inclusive. 
- **hexadecimal numbers** - while most programmers most likely have passing knowledge of hex numbers it might help to include a link to a refresher tutorial or at least mention that the `0x` prefix is used for hex numbers.

**Comment by steveklabnik** [comment]
Good points, all :+1: I'm sure I will accidentally have more of this, and so it'd be good to keep track of things and add either explanations or pointers to explanations.

**Comment by rylev** [comment]
@steveklabnik should we keep this open for all issues that arise around "assumed knowledge" or just open new ones as we see them come up?

**Comment by steveklabnik** [comment]
I actually really like one issue per thing. If you're willing, I would even take closing this issue and opening three, one for each, actually.

Smaller units is easier to get stuff done, and closing them is like checking off a list.

**Comment by rylev** [comment]
Ok closing this in favor of opening each assumed knowledge issue as its own separate Github issue.
