### ISSUE TITLE
3.2 - linker's --nmagic flag on Mac

### ISSUE THREAD

**Issue by jeromefroe** [intermezzOS/book#143]
Hello, I've been working through the book (it's awesome!) but ran into a problem in section 3.2 when I attempt to invoke `ld` with the `--nmagic` flag. Specifically, I see the following output:

```
$ ld --nmagic --output=kernel.bin --script=linker.ld multiboot_header.o boot.o
ld: unknown option: --nmagic
```

I took a look at the [man page for `ld` on Mac](http://www.manpages.info/macosx/ld.1.html) and couldn't find any documentation for `--namgic`, although the [man page for `ld` on Linux](http://linux.die.net/man/1/ld) does document it.

I also read through [issue #30](https://github.com/intermezzOS/book/issues/30) and it seems the flag is essential for continuing. Consequently, I was curious if anyone else has worked through the book on a Mac and ran into a similar issue? 

As a side note I also spun up a Linux VM and have been able to run the command successfully on it.

Thanks!

**Comment by steveklabnik** [comment]
Hello! So yes, you specifically need to not use your system's `ld`: you need to cross-compile an `ld`. 

From the OS X chapter:

> After it is done you should have all the tools you need located in ~/opt. The tools should be named the same as the tools used in other chapters, but they might be prefixed with a x86_64-pc-elf-. The exception to this is grub. 

This of course doesn't make it clear that this means in later chapters that you might need to use `x86_64-pc-elf-ld` instead of just `ld` later, though :/ Leaving this bug open to hopefully make it more clear.

**Comment by jeromefroe** [comment]
Oh, awesome. Sorry for the mix-up, I must have read through that too quickly and didn't realize I should, of course, be using the tools in the `opt/` directory. Really appreciate the help though!

**Comment by steveklabnik** [comment]
Any time! Now that we've merged https://github.com/intermezzOS/book/pull/144, let's give this a close :)

**Comment by SG14-96** [comment]
My ~/opt is empty.As far as i can tell, i have all the tools installed but my linker is not working.

**Comment by steveklabnik** [comment]
If it's empty, it sounds like the script didn't install properly :/
