### ISSUE TITLE
Some versions of xorriso don't install grub-mkrescue

### ISSUE THREAD

**Issue by marnen** [intermezzOS/book#148]
Thanks for the tutorial! One note, though: grub-mkrescue is not installed with certain versions of xorriso (notably the version in the Ubuntu 14.04 package repository). It might be worth mentioning that if you don't have grub-mkrescue after installing everything else, you should install grub-common (at least that's the appropriate Ubuntu package...).

**Comment by steveklabnik** [comment]
Oh interesting! Usually I assume it's "install grub-mkresuce, then install xorriso if you need it" rather than "install xorriso and get grub-mkrescue". We can def make this more clear.

**Comment by marnen** [comment]
@steveklabnik That's especially weird, then; the apt-get install command at the beginning of the book has xorriso, but not the Grub stuff.

**Comment by tyoc213** [comment]
well the windows version installed need to `sudo apt-get install grub-mkrescue`.

**Comment by steveklabnik** [comment]
I'm not working on the first edition anymore, so I'm going to give this a close. This stuff isn't in the second edition, and the build is much easier now and doesn't need this stuff! If someone wants to send in a PR to fix up the first edition, please feel free!
