### ISSUE TITLE
The .nav-chapters.next button overlays the scrollbar

### ISSUE THREAD

**Issue by marijnh** [intermezzOS/book#15]
Which sweeps you through to the next chapter when you're only trying to click the scrollbar.

I couldn't find a low-impact solution, except giving it a `right: 15px`, which is kind of arbitrary and ugly.

**Comment by steveklabnik** [comment]
I believe this has been fixed upstream in the last two years; if not, please let me know! But since I can't reproduce today, I'm going to close.
