### ISSUE TITLE
Boot failed: Could not read from CDROM (code 0004) 

### ISSUE THREAD

**Issue by leroycep** [intermezzOS/book#150]
When booting the iso for the hello world, I got an error saying:

```
Boot failed: Could not read from CDROM (code 0004)
```

@steveklabnik Point me towards the fix for [code 0009](http://intermezzos.github.io/book/appendix/troubleshooting.html#Could%20not%20read%20from%20CDROM%20(code%200009)). The process listed there resolved the issue.

*p.s.* I am using Bash on Ubuntu on Windows, with the XMing program installed to run X11 programs.

**Comment by steveklabnik** [comment]
Looks like this can be closed, as you got things resolved 👍
