### ISSUE TITLE
Compilation problems with xargo

### ISSUE THREAD

**Issue by davidawad** [intermezzOS/book#152]
I'm going through the intermezzos book and I'm having problems compiling the kernel with `xargo` and the rust nightly. 

I don't think that this is a problem related to the book, but I was hoping that I could get some guidance and perhaps provide find some useful input as a non rust programmer with systems experience. I expect that compilation will work after switching to the latest rust nightly but I get some obscure rustup problems that might be simple but I'm not sure as I'm unfamiliar with these tools. Any help is appreciated, thanks in advance! 

I'm on latest MacOS Sierra, and running the latest nightly from rustup. 

```shell
$ rustup default nightly
info: using existing install for 'nightly-x86_64-apple-darwin'
info: default toolchain set to 'nightly-x86_64-apple-darwin'
  nightly-x86_64-apple-darwin unchanged - rustc 1.15.0-nightly (71c06a56a 2016-12-18)

$ rustc --version
rustc 1.15.0-nightly (71c06a56a 2016-12-18)
$ xargo build --release --target x86_64-unknown-intermezzos-gnu --verbose
```
```rust
error: error recursively walking the sysroot
caused by: IO error for operation on /Users/david/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src: No such file or directory (os error 2)
caused by: No such file or directory (os error 2)
stack backtrace:
   0:        0x107dac12e - backtrace::backtrace::trace::hbb3527c862dcb156
   1:        0x107dac43c - backtrace::capture::Backtrace::new::hb88c898ead0c41a6
   2:        0x107d95364 - error_chain::make_backtrace::hf6780bdef7b8a72b
   3:        0x107d91871 - xargo::run::hf26c494eb219d1f4
   4:        0x107d8e11f - xargo::main::h0a087780bc89b4dd
   5:        0x107dcc38a - __rust_maybe_catch_panic
   6:        0x107dcaa06 - std::rt::lang_start::h538f8960e7644c80
```

**Comment by steveklabnik** [comment]
This does seem very strange; I haven't had a lot of time for intermezzOS lately, so I haven't built it in a while. Maybe there's a new bug. I'm not quite sure...

**Comment by bdalenoord** [comment]
The same error occured for me as well, after a bit of Googling I found a bug report for rustup (https://github.com/rust-lang-nursery/rustup.rs/issues/878) which proved the behavior for 'rust-src' has been changed.

You can fix it by calling `rustup component add rust-src`.

After that, everything seems to be compiling happily for me...

**Comment by steveklabnik** [comment]
Ah ha! I should add this to the instructions.

**Comment by dato** [comment]
I also got tons of errors when compiling libc (or was it libc_shims?), though afterwards everything linked and ran successfully.

**Comment by bdalenoord** [comment]
@dato same here, I'm not really sure what would cause these errors though, and as everything else seems to be working I don't think it would be a real problem... The errors only show the first time as well, later runs, even clean ones, are compiling without any problem at all.

**Comment by steveklabnik** [comment]
Also note that `xargo` just released a brand-new version, 0.3.0 https://users.rust-lang.org/t/xargo-v0-3-0-released-build-your-own-std/8571

I don't know if that will make this easier or hard.

**Comment by bdalenoord** [comment]
I've just updated xargo to 0.3.0 and everything seems to work out of the box...

**Comment by steveklabnik** [comment]
I think this issue was transient; @davidawad if you're still having trouble, please let me know and we can re-open, but a *lot* has changed in the past year.
