### ISSUE TITLE
Brew exits script if something is already installed

### ISSUE THREAD

**Issue by 2016rshah** [intermezzOS/book#153]
I had already installed some of the requirements before, so when brew tried to install them it exited by saying they were already installed. This is fine, but as a result the [installation script for mac](http://intermezzos.github.io/book/appendix/osx-install.html) exited also when brew said it was done. As a result, the script never tried to install binutils, gcc, etc. 

I fixed it locally by removing the brew install line, but other than fixing that manually I'm not sure what to change in the script to fix it for others with the same issue.

**Comment by steveklabnik** [comment]
I'm not sure either, as I don't know homebrew. I'd happily take a patch to fix this from someone in the know!

**Comment by emkay** [comment]
I can probably take a look at this sometime over the next week or two since I have home brew and am sort of familiar with the script.

**Comment by courajs** [comment]
So it looks like `brew` exits 0 with a warning if you have the up-to-date version of the package, but exits 1 with an error if you have an older version installed.

I toyed around and figured out how to install only uninstalled packages, but it ignores the issue of versioning:
```bash
BREW_DEPS="gmp mpfr libmpc autoconf automake nasm xorriso qemu"
UNINSTALLED_BREW_DEPS=`comm -23 <(echo $BREW_DEPS|tr ' ' "\n"|sort) <(brew ls|sort)`

brew install $UNINSTALLED_BREW_DEPS
```

`comm` helps you find list differences and intersections, but requires a sorted list of lines.

I could PR if we're comfortable assuming any installed version will work

**Comment by courajs** [comment]
We could alternatively upgrade, offer to upgrade, or exit and tell the user to upgrade any outdated packages

**Comment by ZymoticB** [comment]
Here is a snippet for checking the version of a brew package that may be useful to determine if an upgrade is needed or is the package can be skipped as the version is already required. I just cobbled this together from some other project so there may be some minor issues but hopefully it's a helpful starting point.

```
get_version() {
    local pkg=$1
    if command -v brew > /dev/null 2>&1 ; then
        if brew info $pkg | grep '.*\*$' | grep HEAD > /dev/null 2>&1 ; then
            VERSION="HEAD"
            return
        fi
		# brew info nasm
                # nasm: stable 2.12.02 (bottled), HEAD
                # Netwide Assembler (NASM) is an 80x86 assembler
                # http://www.nasm.us/
                # /usr/local/Cellar/nasm/2.12.02 (29 files, 2M) *
                #   Poured from bottle on 2017-02-22 at 20:10:51
                # From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/nasm.rb
                # ==> Options
                # --universal
                # 	Build a universal binary
                # --HEAD
                # 	Install HEAD version
        if ! VERSION=$(brew info $pkg | grep '.*\*$' | cut -f 1 -d ' ' | awk -F/ '{print $NF}'); then
            echo 0.0.0
        fi
    else
        echo ERROR: unknown package management on this machine
        exit 1
    fi
}

check_version() {
    local target=$1
    local current=$2
    if [ $current = "HEAD" ]; then
       return 0
    fi
    version_arr=( $(echo "$current" | tr '.' ' ') )
    min_version_arr=( $(echo "$target" | tr '.' ' ') )

    if [ ${#version_arr[@]} -ne 3 ]; then
        return 1
    fi

    # version len != 3 is fatal so we just hardcode it here to make the loop expression far simpler
    for i in {0..2}; do
        if [ "${version_arr[$i]}" -lt "${min_version_arr[$i]}" ] ; then
            return 1
        fi
        if [ "${version_arr[$i]}" -gt "${min_version_arr[$i]}" ] ; then
            break
        fi
    done
}

VERSION=$(get_version nasm)
if check_version "2.12.02" "$VERSION" ; then
    brew upgrade nasm || brew install nasm
fi
```

This may be too heavy weight for the appendix which may be striving for simplicity and readability instead of the heavy bash. In that case it's probably best to do something like

```
PKGS= gmp mpfr libmpc autoconf automake nasm xorriso qemu
for pkg in "$PKGS"; do
    brew upgrade "$pkg" || brew install "$pkg"
done
```

**Comment by emkay** [comment]
I would favor upgrade rather than do the version checking. I never really took into consideration the versions of the `brew` packages that would be installed, but tried to keep the script as simple as possible while still being helpful.

@ZymoticB 

```
PKGS= gmp mpfr libmpc autoconf automake nasm xorriso qemu
for pkg in "$PKGS"; do
    brew upgrade "$pkg" || brew install "$pkg"
done
```

seems like it would be cool.

**Comment by ZymoticB** [comment]
The problem IMO is the unconditional upgrade, I'm not a huge fan of that but given this is a consciously run script rather than an unseen side effect I'm okay with it.

I'm happy to make a PR with some initial sign off that this is an acceptable approach. If anyone else takes up the effort be sure to update the description of what the script does [here](http://intermezzos.github.io/book/osx.html)

**Comment by steveklabnik** [comment]
I'm not working on the first edition anymore, so I'm going to give this a close. This stuff isn't in the second edition, as we no longer need these tools to build. It's much easier now! If someone wants to send in a PR to fix up the first edition, please feel free!
