### ISSUE TITLE
Checksums for http downloads in OSX install script

### ISSUE THREAD

**Issue by courajs** [intermezzOS/book#155]
The OSX setup script `curl`s a few http endpoints and runs the code without verification. It should at least verify the packages via checksums

**Comment by steveklabnik** [comment]
I'm not working on the first edition anymore, so I'm going to give this a close. This stuff isn't in the second edition, as we don't need this stuff anymore to build; it's way easier now!. If someone wants to send in a PR to fix up the first edition, please feel free!
