### ISSUE TITLE
Recommend installing mtools on Arch

### ISSUE THREAD

**Issue by Powersource** [intermezzOS/book#158]
Relevant issue? https://github.com/intermezzOS/book/issues/76  
Also, the errors (that were fixed by installing mtools): https://bpaste.net/show/844e8d1249cc

**Comment by steveklabnik** [comment]
Seems good to me!

**Comment by Powersource** [comment]
I just noticed by accident that it's mentioned here (for a different error) https://intermezzos.github.io/book/appendix/troubleshooting.html

**Comment by steveklabnik** [comment]
I'm not working on the first edition anymore, so I'm going to give this a close. This stuff isn't in the second edition, as we no longer need it to build. If someone wants to send in a PR to fix up the first edition, please feel free!
