### ISSUE TITLE
Makefile should respect OSX binary locations.

### ISSUE THREAD

**Issue by ZymoticB** [intermezzOS/book#161]
Section 2.3 does a good job of explaining the requirements of getting your host setup but I feel that that is not true of section 3.5. I haven't figured out the best approach to word this given the incremental nature of that section (which is a great way to introduce the make concepts). Something useful as an end goal could be something along these lines at the top of the Makefile

```
ifeq ($(shell uname -s),Darwin)
BINDIR=$(HOME)/opt/bin/
LD=$(BINDIR)/x86_64-pc-elf-ld
GRUB_MKRESCUE=$(BINDIR)/grub-mkrescue
else
LD=ld
GRUB_MKRESCUE=grub-mkrescue
endif
```

Then throughout the rules should refer to ld as $(LD). I've elided the things installed via brew to keep the amount of make code to a minimum although it is a bit odd to only have a few binaries referred to by absolute paths and variables.

**Comment by steveklabnik** [comment]
I'm not working on the first edition anymore, so I'm going to give this a close. This stuff isn't in the second edition as we no longer need make. If someone wants to send in a PR to fix up the first edition, please feel free!
