### ISSUE TITLE
unknown --nmagic command after setting the $PATH

### ISSUE THREAD

**Issue by mbabatunde** [intermezzOS/book#177]
Hi,

Currently going through the book and enjoying it! I've encountered an issue at section 3.2. 

After writing the linker and using the dynamic linker command `ld` to put the two object files together, I receive the error:
 `ld: unknown option: --nmagic`. 

I ran the script from the appendix and set my path variable for opt/bin on macOS as follows: 
`export PATH="$HOME/opt/bin:$PATH"`. 

Any suggestions on solving this problem?

**Comment by steveklabnik** [comment]
You shouldn't be running `ld`, you should be running `x86_64-pc-elf-ld`. Try that?

**Comment by mbabatunde** [comment]
I get `-bash: x86_64-pc-elf-ld: command not found`

**Comment by steveklabnik** [comment]
Hm. And you did all the setup to compile the cross-compiler stuff in `/opt/bin`?

**Comment by mbabatunde** [comment]
After running the bash script in the appendix, did I have to do additional steps in order to have cross compilation to work?

**Comment by steveklabnik** [comment]
https://github.com/intermezzOS/book/blob/master/src/osx.md

> After it is done you should have all the tools you need located in ~/opt. The tools should be named the same as the tools used in other chapters, but they might be prefixed with a x86_64-pc-elf-. The exception to this is grub. The default path for the binaries installed using the above script is $HOME/opt/bin so adjust the PATH variable appropriately.

So yeah, in my understanding, you should have a `x86_64-pc-elf-ld` inside of `~/opt/bin`.

**Comment by mbabatunde** [comment]
@steveklabnik I'll continue to investigate further. The script worked perfectly, but I guess the linker just isn't there.

Interestingly enough, I don't have a `bin` folder under `~/opt/`

**Comment by steveklabnik** [comment]
That is... very very strange. I don't have access to an OS X machine, so I can't try to diagnose myself :(

**Comment by mbabatunde** [comment]
Yeah, I'm not really sure why it's not working. I will close this issue for now and if I come up with a working solution, I will open it again
