### ISSUE TITLE
problems with compilation

### ISSUE THREAD

**Issue by grinrill** [intermezzOS/book#187]
I can not compile the kernel. the commands I used:
as in the book: 
`$bootimage --target=intermezzos.json`
```
Please invoke `bootimage` with a subcommand (e.g. `bootimage build`).

See `bootimage --help` for more information.
```
other:
`$bootimage build --target intermezzos.json`
```
Building kernel
error: no such subcommand: `xbuild`

        Did you mean `build`?
```
then I ran the command `bootimage build --help` and decided to slightly change the cargo.toml:
```
[package]
name = "intermezzos"
version = "0.1.0"
authors = ["grinr"]

[dependencies]


[package.metadata.bootimage]
default-target = "intermezzos.json"         
output = "bootimage.bin"    
minimum-image-size = 0      

[package.metadata.bootimage.bootloader]
name = "bootloader"                 
version = ""                        
git = ""                          
branch = ""                       
path = ""                         
precompiled = false               
target = "intermezzos.json" 
```

and again started the command:
`$bootimage build --target intermezzos.json`
`Error: Io(Os { code: 3, kind: NotFound, message: "The system can not find the specified path." })`

What else should I do to be compiled?

P.S.: I'm from Russia. I know English badly and therefore translated this text with the help of Google translator.
I'm working on os windows 10.

**Comment by phil-opp** [comment]
You need to install the cargo-xbuild tool:

```
cargo install cargo-xbuild
```

(We should really improve the error messages of bootimage.)

**Comment by grinrill** [comment]
Thank you very much, now everything has worked. As a result, to get the normal result it was necessary to execute the command `cargo install cargo-xbuild` and then compile the command `bootimage build --target intermezzos.json` 
Yes, all this applies to the second edition

**Comment by grinrill** [comment]
but now there is a [problems with qemu](https://github.com/intermezzOS/book/issues/188) :)

**Comment by steveklabnik** [comment]
I've pushed a commit that fixes this in the text :)
