### ISSUE TITLE
problems with running qemu

### ISSUE THREAD

**Issue by grinrill** [intermezzOS/book#188]
The first problem: it was impossible to just run the `qemu-system-x86_64 -version` command because the system said that it does not know what `qemu-system-x86_64` is. I solved this problem by moving to the directory with qemu and starting qemu from there. as a result, this command was obtained for compilation (from the directory with qemu): `qemu-system-x86_64.exe -drive format = raw, file = C: \ ~ \ intermezzos \ bootimage.bin`.

The second problem: when running the above command, qemu gave me this answer:
```
Unexpected error in aio_context_set_poll_params() at /home/stefan/src/qemu/repo.or.cz/qemu/ar7/util/aio-win32.c:413:
qemu-system-x86_64.exe: AioContext polling is not implemented on Windows
```
What should I do next?
Thank you in advance.

P.S.: I'm from Russia. I know English badly and therefore translated this text with the help of Google translator.
I'm working on os windows 10.

**Comment by bjorn3** [comment]
`AioContext polling is not implemented on Windows`: QEMU doesn't work yet on Windows Subsystem for Linux. You could use [virtualbox](https://www.virtualbox.org/) instead.

**Comment by phil-opp** [comment]
Or you can use the native Windows version of QEMU: https://www.qemu.org/download/#windows

**Comment by steveklabnik** [comment]
Yes! We assume that you're using the native WIndows version; if you want to use virtualbox, you *can*, but we don't have good instructions. Thanks!
