### ISSUE TITLE
Entire source of http://intermezzos.github.io/book/ is on a single line

### ISSUE THREAD

**Issue by dholbert** [intermezzOS/book#19]
STR:
1. Visit http://intermezzos.github.io/book/
2. View source (Ctrl+U in Firefox)

ACTUAL RESULTS:
Page source is all on one line, so it's not easily viewable/scrollable.

EXPECTED RESULTS:
Somewhat-easier-to-view page source, with periodic linebreaks, e.g. maybe at the boundaries between major pieces of the page at least.

I presume this page is autogenerated from markdown. I'm hoping/guessing that whatever markdown parser you're using will have that as a feature.

At least, the native GitHub markdown view does insert newlines into the HTML page source, as you can see if you view the source of https://github.com/intermezzOS/book/blob/master/src/preface.md and scroll down.  This is only an issue on the actual intermezzos.github.io-backed version of the page.

(Note that this is distinct from #1, though both issues are about linebreaks.)

**Comment by dholbert** [comment]
![screenshot of "view source" for book in Firefox](https://cloud.githubusercontent.com/assets/426803/12026816/c57e11ee-ad72-11e5-83c0-1662ff83e372.png)

**Comment by steveklabnik** [comment]
Oh interesting! Yeah, this would be a side effect of mdbook. @azerupi, do you know anythig about this?

**Comment by azerupi** [comment]
Indeed, it seems that all the html is rendered on one line. I have to check if it's my code doing that or  rust-handlebars.

**Comment by azerupi** [comment]
My bad, this is actually the same [issue that has been fixed](https://github.com/azerupi/mdBook/pull/78) by @asolove one day ago. So this should be fixed when I upload a new version to crates.io

**Comment by steveklabnik** [comment]
Great! I'm going to give this a close, then, since it will just get fixed upon updating.
