### ISSUE TITLE
Copy button incorrectly copies to clipboard

### ISSUE THREAD

**Issue by mtn** [intermezzOS/book#191]
Hi!

This might (and seems likely to) be a `mdbook` issue, rather than something to do with this project. However, since I haven't worked with `mdbook`, I figured it'd be better to make the issue here first in case I'm just misunderstanding intended behavior.

 When I use the copy to clipboard button in the first example [here](https://intermezzos.github.io/book/second-edition/hello-world/setting-up-a-project.html#removing-the-standard-library), somehow the code copies incorrectly (there's a `main` defined). Similarly, the result of copying to clipboard for the second example is different from what I expected.

I haven't dug into any of the code, except for rebuilding the book locally to make sure it wasn't something that would just go away. Maybe this a bug?

Edit: Having tried a minimal example, I'm pretty sure this has nothing to do with `intermezzOS`. I'll leave this open in case I'm just confusing something, for now.

**Comment by steveklabnik** [comment]
Ahh interesting. Yes, it's an mdbook issue, and a subtle one. Would you like to open a bug upstream, or should I?

**Comment by mtn** [comment]
Thanks -- I opened an issue upstream.
