### ISSUE TITLE
Paging explanation

### ISSUE THREAD

**Issue by npip99** [intermezzOS/book#195]
http://intermezzos.github.io/book/first-edition/paging.html

I'm not sure if this is the best way to describe the usefulness of paging. I mean, we already have to be careful over what we use for memory (To not use VGA mapped memory at 0xb8000, for example), so inventing a completely new construct to make sure that we don't go beyond the limits of RAM doesn't seem to make any sense to me. We could just have a size MAX_ADDR that our kernel isn't allowed to go beyond, so implementing a check for that when allocating memory seems so much easier than assuming we don't try paging too many things. Paging too many things will have to check against this theoretical "MAX_ADDR" anyway.

I think for paging, the idea of virtual memory mapping is more important. Perhaps, just explain that

"if you run the same program twice, it will need to use the same addresses [Since their assembler code is using all of the same pointers]. We can't have that, so we handle a page table. When we swap programs, we give it a new page table so the "same" location in memory for the program points to somewhere unique in the physical RAM.", perhaps not quoted but something along those lines (Which appears to be fewer characters than the existing explanation, though it's a bit more dense). Perhaps throw in [this](https://en.wikipedia.org/wiki/Virtual_address_space#/media/File:Virtual_address_space_and_physical_address_space_relationship.svg) and a little hand-waving. Ofc, there's not much hardcoded stuff anyway because of things like ASLR, but it's a better description in my opinion. Maybe also throw in a note that "If they're out of bounds, we can catch it as them accessing a page that hasn't been mapped to a physical address yet. Then we crash their program for behaving poorly. This is much better than having them mess with 0xb8000!".

If it's really too much (Which it might be), it'd be possible to just remove the RAM out of bound explanation and replace it with the "By the way..." text to avoid the virtual memory talk (This might honestly be the best idea here). Still, the old 8086 did just fine keeping people in bounds without paging, though RAM could just span the entire address space in those days [It didnt always have to, so it ends up being the same out of bounds problem].

That's just my two cents.

**Comment by steveklabnik** [comment]
Thank you for the feedback! We're freezing the first edition though, so this isn't going to be fixed. I'll keep this in mind for when we get to paging in the second edition.

**Comment by npip99** [comment]
Awh really? I absolutely loved the first edition (I didn't even realize there was a second, Whoops, I'll check it out after though). I would've liked to see the first edition expanded into a comprehensive "assembly" to "here's a shell". (Was slightly sad I couldn't see real mode to protected mode but I used another tutorial to fill that one in and then accepted the use of GRUB)
