### ISSUE TITLE
Diagrams

### ISSUE THREAD

**Issue by steveklabnik** [intermezzOS/book#2]
https://github.com/intermezzOS/book/commit/d73c6b1b4a4b641d9e803ace60324bdcfe0b5405 introduced a few places where we need some diagrams.

@ag_dubs says she wants to help out here :)

Ashley, let me know if you need help with what the diagrams should look like; i'm just imagining boxes.

**Comment by ashleygwilliams** [comment]
thoughts? 
![screenshot 2015-12-25 at 8 16 27 pm](https://cloud.githubusercontent.com/assets/1163554/12004776/67fd945c-ab44-11e5-97c6-26715e68650f.png)

**Comment by steveklabnik** [comment]
There's one last one missing, the hypervisor.
