### ISSUE TITLE
Re-watch "simple vs easy" and finish that paragraph

### ISSUE THREAD

**Issue by steveklabnik** [intermezzOS/book#27]
http://intermezzos.github.io/book/multiboot-headers.html

**Comment by common-nighthawk** [comment]
I would also add a link to the video.  It looks like it can be found here--
http://www.infoq.com/presentations/Simple-Made-Easy

**Comment by jdanford** [comment]
Also, make sure to change the title in the book from "Simple vs. Easy" to "Simple Made Easy"

**Comment by steveklabnik** [comment]
I'm not working on the first edition actively anymore, and this section no longer exists. As such, I'm going to close it.
