### ISSUE TITLE
Could not read from CDROM (code 0009)

### ISSUE THREAD

**Issue by tech-and-techno** [intermezzOS/book#35]
In case you get this when trying to boot the ISO image in QEMU:
Could not read from CDROM (code 0009)

on Ubuntu run:

```
$ sudo apt-get install grub-pc-bin
```

now try again to make the ISO and run it in QEMU:

```
$ grub-mkrescue -o os.iso isofiles
$ qemu-system-x86_64 -cdrom os.iso
```

At the bottom of http://wiki.osdev.org/Bare_Bones  is the reason of that error message.

**Comment by varjmes** [comment]
Thanks @d1maz, I just got to this step and had the same problem! This worked :)

**Comment by steveklabnik** [comment]
I'm thinking about starting a 'common troubleshooting' chapter with these kinds of answers in it.

**Comment by varjmes** [comment]
Sounds like a good idea!

**Comment by steveklabnik** [comment]
I'm thinking of organizing it per-chapter so it doesn't get huge, too. :)

**Comment by tech-and-techno** [comment]
Yes, this is a great idea.

I think a lot of people would stop follow this awesome project, when some unexpected errors/bugs pop up and they can't find solutions for them. So some kind of troubleshooting will definitely be helpful and desirable. =)

**Comment by steveklabnik** [comment]
Let me make a new issue so as not to distract this one :)

**Comment by rylev** [comment]
This is now addressed in the troubleshooting appendix. https://github.com/intermezzOS/book/pull/60
