### ISSUE TITLE
grub-mkrescue fails with "Cannot find path 'efi.img' in loaded ISO image"

### ISSUE THREAD

**Issue by omivore** [intermezzOS/book#45]
When building the .iso file, grub-mkrescue aborted with the error
`xorriso : FAILURE : Cannot find path '/efi.img' in loaded ISO image`

This from the command given in 3.3 Making an ISO.

**Comment by omivore** [comment]
Solved by installing mtools, which, from my scant research, seems to only be an optional dependency for grub. Apparently grub is "trying to apply efi support when there is none" or something like that.

A simple `sudo apt-get install mtools` or equivalent variant solves that. Works for me, but I saw something about options for grub-mkrescue somewhere, or at least a bug report for grub, if anyone wants to look further. Regardless, I ran into this problem and this is what I did to fix it. Hopefully it'll help others.

**Comment by steveklabnik** [comment]
Seems like another awesome candidate for https://github.com/intermezzOS/book/issues/43
