### ISSUE TITLE
Finished Makefile expects grub.cfg to be in the root level

### ISSUE THREAD

**Issue by omivore** [intermezzOS/book#46]
This probably got left behind in the midnight writing spree, but the makefile copies grub.cfg on the root level into build/isofiles/boot/grub, assuming that grub.cfg is at the aforementioned root level. But anyone following along would have grub.cfg still buried in isofiles/boot/grub.

**Comment by steveklabnik** [comment]
Yes! I haven't fully covered that yet. :+1:

**Comment by omivore** [comment]
Okay, thought something on those lines have happened. I guess I shouldn't be critiquing a half-finished product, sorry about that. (Also just sent off another issue :P Once again, sorry!)

**Comment by steveklabnik** [comment]
I would MUCH prefer too many issues than too few :) send 'em all!
