### ISSUE TITLE
QEMU video doesn't work

### ISSUE THREAD

**Issue by rothwerx** [intermezzOS/book#48]
In section 3.4, "Running in QEMU", when running 
`$ qemu-system-x86_64 -cdrom os.iso`
I get the following when executed over ssh or VM console:
`Could not initialize SDL(No available video device) - exiting`

Running `qemu-system-x86_64 -curses -cdrom os.iso` works. Though instructions on how to exit the emulator would be great too.

Debian Jessie on VirtualBox 5.0.0.

By the way, this is a great tutorial. Everything has been explained very well so far.

**Comment by steveklabnik** [comment]
> By the way, this is a great tutorial. Everything has been explained very well so far.

Thanks!

Overall, this issue sounds like a candidate for https://github.com/intermezzOS/book/issues/43

> Though instructions on how to exit the emulator would be great too.

That's being discussed over at https://github.com/intermezzOS/kernel/issues/12, which could be in either repository, frankly, but it was opened there first.
