### ISSUE TITLE
Is this a collaborative writing thing?

### ISSUE THREAD

**Issue by dvberkel** [intermezzOS/book#55]
I just want to start a discussion about if and how help writing intermezzOS could be a thing. I love the project and but I realize this could be a huge time sink for a single person. I have absolutely now experience with assembly for the `x86_64` platform, but I am fairly conversant with git and could probably write a large portion of that chapter. I confidently assume that others could contribute in a meaningful way as well.

So my question is. Is collaborative writing something that is interesting, or should it not be pursued. If it is interesting, how do we implement it?

**Comment by steveklabnik** [comment]
Hey @dvberkel ! There's actually an RFC issue open about this: https://github.com/intermezzOS/rfcs/issues/4

Basically, I am not 100% sure. I really like getting help from people, but writing is a personal thing, so like, if someone wrote a chapter and then I made a ton of edits, would their feelings get hurt? That kind of thing is what I'm worried about.

Anyway, let's talk about it over there!
