### ISSUE TITLE
Memory mapping

### ISSUE THREAD

**Issue by dariusk** [intermezzOS/book#56]
I'm wondering if it's worth having an aside on the concept of memory mapping. It's mentioned twice in [Hello, world!](http://intermezzos.github.io/book/hello-world.html) without any explanation. If you think it's worthwhile, I'm happy to volunteer since this is 100% the kind of thing I like writing about in the voice of this book.

**Comment by steveklabnik** [comment]
Oh yeah, I'm open to this for sure. :)

**Comment by rylev** [comment]
This sounds awesome :heart:
