### ISSUE TITLE
Appendix: Signed and Unsigned Integers

### ISSUE THREAD

**Issue by dariusk** [intermezzOS/book#70]
Currently a stub. @rylev volunteered to tackle this. Possibly of interest is my partial attempt to define signed integers that didn't make it into another PR:

https://gist.github.com/dariusk/505305e584bd8a2006f5

**Comment by steveklabnik** [comment]
I'm not working on the first edition anymore, so I'm going to give this a close. This stuff isn't in the second edition yet, and it's not likely to make it exactly. If someone wants to send in a PR to fix up the first edition, please feel free!
