### ISSUE TITLE
slightly incorrect statement about asm

### ISSUE THREAD

**Issue by steveklabnik** [intermezzOS/book#82]
> "Assembly language gives us direct access to a specific machine. If the basis of computer science is abstraction, the very bottom of the software abstraction layer is assembly. Below it lies only hardware and physics."

This is not strictly true, especially on x86. microcode :(

**Comment by tyoc213** [comment]
Assembly and the opcodes it generated through and assembler.... the wording to explain all easely how wil be?

**Comment by steveklabnik** [comment]
I'm not working on the first edition anymore, so I'm going to give this a close. This stuff isn't in the second edition yet, and it's not likely to make it exactly. If someone wants to send in a PR to fix up the first edition, please feel free!
