### ISSUE TITLE
Consistently use 0x notation for hexadecimal values.

### ISSUE THREAD

**Issue by fiveop** [intermezzOS/book#86]
It was introduced before https://github.com/intermezzOS/book/blame/master/src/hello-world.md#L172 but is not used at this location, leading to ambiguous sentences.

**Comment by tyoc213** [comment]
I vote that the hexadecimal is explained trought the introduction of nibbles, so you can teach counting up to 0xF, 0xFF, 0xFFFF and know the inmediate transition to 0b1111,  0b1111_1111, and it also introduces a little rust syntaxis on this.

**Comment by steveklabnik** [comment]
I'm not working on the first edition anymore, so I'm going to give this a close.  If someone wants to send in a PR to fix up the first edition, please feel free!
